on:
  workflow_dispatch:
  pull_request:

name: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - run: pnpm test:e2e
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
